<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-DCEJNHE" failures="1" tests="1" name="Test" time="17.416" errors="0" timestamp="2022-03-14T23:32:53 CET">
  <testcase classname="MyFramework.SomeTestToFail" name="testToFail" time="13.006">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at MyFramework.SomeTestToFail.testToFail(SomeTestToFail.java:39)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- testToFail -->
</testsuite> <!-- Test -->
